### ISSUE TITLE
Login a la segunda

### ISSUE THREAD

**Issue by eloyhz** [acominf/RequisitorDeVentas#4]
Revisar porque se tiene que hacer login dos veces en el servidor de Cloud9 y corregirlo.

**Comment by ICAnthonyR** [comment]
problema del explorador? usando mozilla firefox  no crea el error.

**Comment by ICAnthonyR** [comment]
trabajando con chorme vara evitar falla

**Comment by ICAnthonyR** [comment]
se re direcciona directo al index
